import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import { inter, poppins } from "@/fonts/fonts";
import Navbar from "@/components/Navbar/Navbar";
import Provider from "@/components/Provider/Provider";

import DrawerMenu from "@/components/DrawerMenu/DrawerMenu";

import "swiper/css";
import "./globals.css";
import { notFound } from "next/navigation";
import { useMessages } from "next-intl";
import { LOCALES } from "@/i18n.config";
import ExcludeLoginRegisterWrapper from "@/components/ExcludeLoginRegisterWrapper/ExcludeLoginRegisterWrapper";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    params: { locale },
}: {
    children: React.ReactNode;
    params: { locale: string };
}) {
    if (!LOCALES.includes(locale as any)) notFound();
    const messages = useMessages();
    return (
        <html lang={locale}>
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased dark",
                    inter.variable,
                    poppins.variable
                )}
            >
                <Provider locale={locale} messages={messages}>
                    <div className="flex">
                        <ExcludeLoginRegisterWrapper>
                            <Navbar />
                            <DrawerMenu />
                        </ExcludeLoginRegisterWrapper>
                        <div className="ml-auto  h-screen transition-all w-full lg:peer-[&.active]/drawer:w-[calc(100%_-_var(--drawer-menu-width))]">
                            {children}
                        </div>
                    </div>
                </Provider>
            </body>
        </html>
    );
}
